apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    app: crayfits
  name: crayfits
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crayfits
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ../kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        app: crayfits
    spec:
      containers:
      - image: islandora/crayfits:latest
        name: crayfits
        resources: {}
      restartPolicy: Always
status: {}
