apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    app: fits
  name: fits
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fits
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ../kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        app: fits
    spec:
      containers:
      - image: islandora/fits:latest
        name: fits
        resources: {}
      restartPolicy: Always
status: {}
