apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: matomo
  name: matomo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matomo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: matomo
    spec:
      containers:
      - env:
        - name: MATOMO_DB_PASSWORD
          value: password
        - name: MATOMO_DB_ROOT_PASSWORD
          value: password
        - name: MATOMO_SITE_HOST
          value: islandora.idc.localhost
        - name: MATOMO_SITE_TIMEZONE
          value: America/Halifax
        - name: MATOMO_USER_EMAIL
          value: admin@example.org
        - name: MATOMO_USER_PASS
          value: $2y$10$S38e7HPM9LI3aOIvcnRsfuMCm4ipNP572QsvbCK60upoHVJ61hMrS
        image: islandora/matomo:latest
        name: matomo
        resources: {}
        volumeMounts:
        - mountPath: /var/www/matomo
          name: matomo-config-data
      restartPolicy: Always
      volumes:
      - name: matomo-config-data
        persistentVolumeClaim:
          claimName: matomo-config-data
status: {}
