apiVersion: v1
kind: PersistentVolume
metadata:
  name: activemq-data
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain

  # TODO Finish this.  I need to boot up my Mac to test