apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: activemq
  name: activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: activemq
    spec:
      containers:
      - env:
        - name: ACTIVEMQ_PASSWORD
          value: password
        - name: ACTIVEMQ_WEB_ADMIN_PASSWORD
          value: password
        image: islandora/activemq:latest
        name: activemq
        resources: {}
        volumeMounts:
        - mountPath: /opt/activemq/data
          name: activemq-data
      restartPolicy: Always
      volumes:
      - name: activemq-data
        persistentVolumeClaim:
          claimName: activemq-data
status: {}
