apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: cantaloupe
    app: cantaloupe
  name: cantaloupe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cantaloupe
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cantaloupe
    spec:
      containers:
      - image: islandora/cantaloupe:latest
        name: cantaloupe
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: cantaloupe-data
      restartPolicy: Always
      volumes:
      - name: cantaloupe-data
        persistentVolumeClaim:
          claimName: cantaloupe-data
status: {}
