apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: crayfits
  name: crayfits
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crayfits
  strategy: {}
  template:
    metadata:
      labels:
        app: crayfits
    spec:
      containers:
      - image: islandora/crayfits:latest
        name: crayfits
        resources: {}
      restartPolicy: Always
status: {}
