apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fits
  name: fits
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fits
  strategy: {}
  template:
    metadata:
      labels:
        app: fits
    spec:
      containers:
      - image: islandora/fits:latest
        name: fits
        resources: {}
      restartPolicy: Always
status: {}
