apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: milliner
  name: milliner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milliner
  strategy: {}
  template:
    metadata:
      labels:
        app: milliner
    spec:
      containers:
      - image: islandora/milliner:latest
        name: milliner
        resources: {}
      restartPolicy: Always
status: {}
