apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solr
  name: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: solr
    spec:
      containers:
      - image: islandora/solr:latest
        name: solr
        resources: {}
        volumeMounts:
        - mountPath: /opt/solr/server/solr
          name: solr-data
      restartPolicy: Always
      volumes:
      - name: solr-data
        persistentVolumeClaim:
          claimName: solr-data
status: {}
